---
- hosts: zookeeper
  remote_user: root
  tasks:
    - include: tasks/install_java.yml
    - include: tasks/open_ports.yml
    - include: tasks/install_zookeeper.yml




# - hosts: kafka
#   remote_user: root
#   tasks:
#   - name: Update and upgrade apt packages
#     become: true
#     apt:
#       upgrade: yes
#       update_cache: yes
#       cache_valid_time: 86400 #One day
#   - name: Install OpenJDK
#     become: true
#     apt:
#       name: default-jdk
#   - name: Install Zookeeper
#     become: true
#     apt:
#       name: zookeeperd
