- name: Remove data and log directory

  become: true
  file:
    state: absent
    path: "{{ item }}/"
  loop:
    - /usr/local/kafka_{{ scala_version }}-{{ kafka_version }}
    - /var/log/zookeeper
    - /etc/init.d/kafka
