- name: Download Kafka {{ kafka_version }} and Unarchive
  become: true
  unarchive:
    src: 'http://mirrors.koehn.com/apache/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz'
    dest: /usr/local
    remote_src: yes

- name: Copy server.properties file
  become: true
  template:
    src: 'server.properties.j2'
    dest: '/usr/local/kafka_{{ scala_version }}-{{ kafka_version }}/config/server.properties'



# - hosts: kafka
#   remote_user: root
#   tasks:
#   - name: Update and upgrade apt packages
#     become: true
#     apt:
#       upgrade: yes
#       update_cache: yes
#       cache_valid_time: 86400 #One day
#   - name: Install OpenJDK
#     become: true
#     apt:
#       name: default-jdk
#   - name: Install Zookeeper
#     become: true
#     apt:
#       name: zookeeperd
