- name: Download Kafka {{ kafka_version }} and Unarchive
  become: true
  unarchive:
    src: 'http://mirrors.koehn.com/apache/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz'
    dest: /usr/local
    remote_src: yes

- name: Copy server.properties file
  become: true
  template:
    src: '../templates/server.properties.j2'
    dest: '/usr/local/kafka_{{ scala_version }}-{{ kafka_version }}/config/server.properties'

- name: Create log directory
  become: true
  file:
    path: /usr/local/kafka_{{ scala_version }}-{{ kafka_version }}/logs
    state: directory
    mode: 0755

- name: Copy init.d file
  become: true
  template:
    src: '../templates/kafka.j2'
    dest: '/etc/init.d/kafka'
    mode: 0755

- name: Remove to /etc/security/limits.conf
  become: true
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  loop:
    - "* soft nofile 2097152"
    - "* hard nofile 2097152"

- name: Add to /etc/pam.d/common-session
  become: true
  lineinfile:
    path: /etc/pam.d/common-session
    line: "session required pam_limits.so"

- name: Add to /etc/sysctl.conf
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    line: "fs.file-max = 2097152"

- name: Sync settings
  become: true
  shell: sysctl -p
