- name: Stop the Kafka service, if running.
  become: true
  service:
    name: kafka
    state: stopped
    enabled: yes

- name: Start the Kafka service.
  become: true
  service:
    name: kafka
    state: started
