- name: Stop the Superset server, if running
  shell: pgrep gunicorn | xargs kill -2

- name: Start the Superset server
  shell: gunicorn -w 2 --timeout 60 -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app >> superset.log 2>&1 &
