---
- hosts: kafka
  vars:
    scala_version: "2.10"
    kafka_version: "0.10.0.1"
  remote_user: root
  serial: 1
  tasks:
    - include: ../tasks/stop_kafka.yml

- hosts: kafka
  vars:
    scala_version: "2.10"
    kafka_version: "0.10.0.1"
  remote_user: root
  tasks:
    - include: ../tasks/clean_kafka.yml
