---
- hosts: zookeeper
  remote_user: root
  serial: 1
  tasks:
    - include: ../tasks/stop_zookeeper.yml

- hosts: zookeeper
  remote_user: root
  tasks:
    - include: ../tasks/clean_zookeeper_data.yml

- hosts: zookeeper
  remote_user: root
  serial: 1
  tasks:
    - include: ../tasks/start_zookeeper.yml
